require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Force building pods for Intel when building for simulators
def force_intel_for_simulators(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force CocoaPods targets to always build for x86_64
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end
end

platform :ios, '11.0'

target 'BraintreeDropInErrorRepro' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'BraintreeDropIn', :inhibit_warnings => true

  target 'BraintreeDropInErrorReproTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    force_intel_for_simulators(installer)
  end
end
